name: xproj-docs
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - pyproj
  - sphinx
  - pydata-sphinx-theme=0.15.4
  - sphinx-book-theme=1.1.3
  - sphinx-autosummary-accessors
  - myst-nb
  - pip
